<?xml version='1.0'?>
<robot name="myrobot" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <robot_param>robot_description</robot_param>
      <robot_param_node>robot_state_publisher</robot_param_node>
      <parameters>/home/ty/f1test_ws/ar-tu-do/control_config.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- ROS2 Control Interfaces -->
  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <!-- Rear Wheel Drive Joints -->
    <joint name="left_wheel_back_hinge">
      <command_interface name="velocity">
        <param name="min">-100</param>
        <param name="max">100</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="right_wheel_back_hinge">
      <command_interface name="velocity">
        <param name="min">-100</param>
        <param name="max">100</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <!-- Front Wheel Steering Joints -->
    <joint name="left_steering_hinge">
      <command_interface name="position">
        <param name="min">-1.0</param>
        <param name="max">1.0</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="right_steering_hinge">
      <command_interface name="position">
        <param name="min">-1.0</param>
        <param name="max">1.0</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <xacro:arg name="simulation" default="false"/>

  <xacro:if value="$(arg simulation)">
    <xacro:include filename="$(find racer_description)/urdf/racer_plugins.gazebo" />
  </xacro:if>
  <xacro:include filename="$(find racer_description)/urdf/racer_macros.xacro" />

  <xacro:property name="cameraSizeL" value="0.03"/>
  <xacro:property name="cameraSizeB" value="0.03"/>
  <xacro:property name="cameraSizeH" value="0.17"/>
  <xacro:property name="cameraMass" value="0.1"/>

  <xacro:property name="hokuyoSize" value="0.1"/>
  <xacro:property name="hokuyoMass" value="0.1"/>

  <xacro:property name="bodySizeL" value="0.49"/>
  <xacro:property name="bodySizeB" value="0.18"/>
  <xacro:property name="bodySizeH" value="0.1"/>
  <xacro:property name="bodyMass" value="3.5"/>

  <!-- Wheel properties -->
  <xacro:property name="wheel_radius" value="0.05" /> 
  <xacro:property name="wheel_height" value="0.045" />
  <xacro:property name="wheel_mass" value="0.2" />
  
  <xacro:property name="base_x_origin_to_wheel_origin" value="0.16" />
  <xacro:property name="base_y_origin_to_wheel_origin" value="0.1055" />
  <xacro:property name="base_z_origin_to_wheel_origin" value="0" />
  <xacro:property name="base_x_sphere_origin_to_wheel_origin" value="0.000" />
  <xacro:property name="base_y_sphere_origin_to_wheel_origin" value="0.001" />
  <xacro:property name="base_z_sphere_origin_to_wheel_origin" value="0" />
  
  <!-- Steering properties -->
  <xacro:property name="steering_radius" value="0.01" /> 
  <xacro:property name="steering_mass" value="0.07" />

  <link name="base_link" />

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="chassis" />
  </joint>

  <!--  Body  -->
  <link name='chassis'>
    <inertial>
      <mass value="${bodyMass}"/>
      <origin xyz="0 0 ${wheel_height/2}" rpy=" 0 0 0"/>
      <xacro:box_inertia m="${bodyMass}" l="${bodySizeL}" b="${bodySizeB}" h="${bodySizeH}" />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 ${wheel_height/2}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${bodySizeL} ${bodySizeB} ${bodySizeH}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="file:///home/ty/f1test_ws/ar-tu-do/ros_ws/install/racer_description/share/racer_description/meshes/car.dae"/>
      </geometry>
      <material name="car_material">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/Orange</material>
  </gazebo>

  <joint name="base_body_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="body" />
  </joint>

  <link name='body'>
    <visual>
      <origin xyz="0 0 0.05" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="file:///home/ty/f1test_ws/ar-tu-do/ros_ws/install/racer_description/share/racer_description/meshes/body.dae"/>
      </geometry>
    </visual>
  </link>

  <gazebo reference="body">
    <material>Gazebo/Blue</material>
  </gazebo>

    <!--  Wheels  -->
  <xacro:wheel fb="front" lr="left" parent="left_steering" translateX="1" translateY="1" left="1" OffsetJointX= "${base_x_sphere_origin_to_wheel_origin}" OffsetJointY= "${base_y_sphere_origin_to_wheel_origin}" OffsetJointZ= "${base_z_sphere_origin_to_wheel_origin}" OffsetY="0.02" />

  <xacro:wheel fb="front" lr="right" parent="right_steering" translateX="1" translateY="-1" left="0" OffsetJointX= "${base_x_sphere_origin_to_wheel_origin}" OffsetJointY= "${base_y_sphere_origin_to_wheel_origin}" OffsetJointZ= "${base_z_sphere_origin_to_wheel_origin}" OffsetY="-0.02" />

  <xacro:wheel fb="back" lr="left" parent="chassis" translateX="-1" translateY="1" left="1" OffsetJointX= "${base_x_origin_to_wheel_origin}" OffsetJointY= "${base_y_origin_to_wheel_origin}" OffsetJointZ= "${base_z_origin_to_wheel_origin}" OffsetY="0.021" />

  <xacro:wheel fb="back" lr="right" parent="chassis" translateX="-1" translateY="-1" left="0" OffsetJointX= "${base_x_origin_to_wheel_origin}" OffsetJointY= "${base_y_origin_to_wheel_origin}" OffsetJointZ= "${base_z_origin_to_wheel_origin}" OffsetY="-0.021" />

  <!-- Steering -->
  <xacro:steering_hinge lr="left" parent="chassis" translateY="1" OffsetY="0.01" />
  <xacro:steering_hinge lr="right" parent="chassis" translateY="-1" OffsetY="-0.01" />

  <!-- Camera -->
  <link name="camera">
    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <xacro:box_inertia m="${cameraMass}" l="${cameraSizeL}" b="${cameraSizeB}" h="${cameraSizeH}" />
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSizeL} ${cameraSizeH} ${cameraSizeB}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file:///home/ty/f1test_ws/ar-tu-do/ros_ws/install/racer_description/share/racer_description/meshes/ZED.dae"/>
      </geometry>
    </visual>
  </link>

  <gazebo reference="camera">
    <material>Gazebo/Red</material>
  </gazebo>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.21 0 0.095" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="laser">
    <inertial>
      <mass value="${hokuyoMass}" />
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <xacro:box_inertia m="${hokuyoMass}" l="${hokuyoSize}" b="${hokuyoSize}" h="${hokuyoSize}" />
    </inertial>

    <collision>
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${hokuyoSize} ${hokuyoSize} ${hokuyoSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file:///home/ty/f1test_ws/ar-tu-do/ros_ws/install/racer_description/share/racer_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>

  <gazebo reference="laser">
    <material>Gazebo/Green</material>
  </gazebo>

  <joint name="laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.21 0 0.135" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="laser"/>
  </joint>

  <!-- IMU -->
  <link name="imu_link" />

  <joint name="imu_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 0.135" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="imu_link"/>
  </joint>

</robot>