<?xml version='1.0'?>

<robot name="racer_test" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="simulation" default="false"/>

  <xacro:if value="$(arg simulation)">
    <xacro:include filename="$(find racer_description)/urdf/racer_plugins.gazebo" />
  </xacro:if>

  <xacro:property name="bodySizeL" value="0.49"/>
  <xacro:property name="bodySizeB" value="0.18"/>
  <xacro:property name="bodySizeH" value="0.1"/>
  <xacro:property name="bodyMass" value="3.5"/>

  <xacro:property name="wheel_radius" value="0.05" /> 
  <xacro:property name="wheel_height" value="0.045" />
  <xacro:property name="wheel_mass" value="0.2" />

  <link name="base_link" />

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="chassis" />
  </joint>

  <!--  Main Body with basic geometry -->
  <link name='chassis'>
    <inertial>
      <mass value="${bodyMass}"/>
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${bodySizeL} ${bodySizeB} ${bodySizeH}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${wheel_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${bodySizeL} ${bodySizeB} ${bodySizeH}"/>
      </geometry>
      <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/Orange</material>
  </gazebo>

  <!-- Simple wheels -->
  <link name="left_wheel_front">
    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0 0 0" rpy="${90*pi/180} 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy="${90*pi/180} 0 0" />
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${90*pi/180} 0 0" /> 
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}" />
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>      
  </link>

  <gazebo reference="left_wheel_front">
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="left_wheel_front_hinge" type="continuous">
    <parent link="chassis"/>
    <child link="left_wheel_front"/>
    <origin xyz="0.16 0.1055 0" rpy="0 0 0" /> 
    <axis xyz="0 1 0" rpy="0 0 0" />
    <limit effort="20" velocity="500"/>
  </joint>

  <!-- Right front wheel -->
  <link name="right_wheel_front">
    <inertial>
      <mass value="${wheel_mass}" />
      <origin xyz="0 0 0" rpy="${90*pi/180} 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy="${90*pi/180} 0 0" />
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${90*pi/180} 0 0" /> 
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}" />
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>      
  </link>

  <gazebo reference="right_wheel_front">
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="right_wheel_front_hinge" type="continuous">
    <parent link="chassis"/>
    <child link="right_wheel_front"/>
    <origin xyz="0.16 -0.1055 0" rpy="0 0 0" /> 
    <axis xyz="0 1 0" rpy="0 0 0" />
    <limit effort="20" velocity="500"/>
  </joint>

</robot>